### ISSUE TITLE
Multiple database support.

### ISSUE THREAD

**Issue by ghost** [floatdrop/express-mongo-db#11]
My application uses two databases, one for application operations, and one for heavy analytical data queries. It would be nice to allow for 2+ databases to be passed through the request by default.

**Comment by floatdrop** [comment]
@CTucker1327 you can add two instances of `expressMongoDb`:

``` js
var app = require('express')();

var expressMongoDb = require('express-mongo-db');
app.use(expressMongoDb('mongodb://database1/test'));
app.use(expressMongoDb('mongodb://database2/test', {property: 'db2'}));

app.get('/', function (req, res, next) {
    req.db // => Db object
    req.db2 // => Db object
});
```
