### ISSUE TITLE
Reusing MongoDB connection for sessions

### ISSUE THREAD

**Issue by reggi** [floatdrop/express-mongo-db#6]
Really like this project. I'm looking to use mongo for a session store and for a database.
Ideally I'd love to open one connection for both.

Is there a way I can do this using `node-mongo-native` and pipe that to both `connect-mongo` and `express-mongo-db`? Ideally I can pass in a Mongo URL once, one connection is established for both.

This is my working current code, I believe making two connections.

``` javascript
app.use(require('express-mongo-db')(Promise.promisifyAll(require('mongodb')), mongodbUri.parse(process.env.MONGO_URI)))
app.use(session({
  secret: process.env.SESSION_SECRET,
  store: new MongoStore({"url": process.env.MONGO_URI}),
  resave: true,
  saveUninitialized: false
}));
```

**Comment by floatdrop** [comment]
Thanks. I think this is answer to your question - https://github.com/kcbanner/connect-mongo#re-use-a-native-mongodb-driver-connection

``` js
app.use(require('express-mongo-db')(Promise.promisifyAll(require('mongodb')), mongodbUri.parse(process.env.MONGO_URI)))
app.use(function (req, res, next) {
    session({
        secret: process.env.SESSION_SECRET,
        store: new MongoStore({db: req.db}),
        resave: true,
        saveUninitialized: false
    })(req, res, next);
});
```

**Comment by reggi** [comment]
Amazing thanks a bunch!
