### ISSUE TITLE
Is checking if available on every request harmful.

### ISSUE THREAD

**Issue by reggi** [floatdrop/express-mongo-db#7]
The code checks if theres a connection available every request. Is this harmful?

https://github.com/floatdrop/express-mongo-db/blob/master/index.js#L27

**Comment by floatdrop** [comment]
This is not "checking" for available connection, so no - it is not harmful.

`available` comes from [connect-once](https://github.com/floatdrop/connect-once) and emitted when first connection available or right away (when it is cached).

**Comment by reggi** [comment]
Thanks for the explanation!
