### ISSUE TITLE
Using mongodb promise

### ISSUE THREAD

**Issue by reggi** [floatdrop/express-mongo-db#8]
With `1.0.0` I was doing this:

``` js
var mongodb = Promise.promisifyAll(require('mongodb'))
var mongodbUri = require('mongodb-uri')

router.use(expressMongodb(mongodb, mongodbUri.parse(uri)))
```

I don't believe this is supported anymore, how would I achieve the same?

**Comment by reggi** [comment]
Seems I've been out of the loop, the mongodb client supports promises natively now?

**Comment by floatdrop** [comment]
@reggi yep, they adopted promises at module level.
